### ISSUE TITLE
Sentence boundaries

### ISSUE THREAD

**Issue by apepa** [TalSchuster/VitaminC#2]
Hi,

Thank you for the great work!

I wanted to check whether it is possible to get a version of the dataset splits that has cleaner sentence boundaries.
Right now there are records with different spacing before/after a punctuation mark, which makes it difficult to split into sentences with simple sentence tokenizers from spacy/nltk, e.g. no spacing after a dot at the end of a sentence or spacing after a final dot in an abbreviation:

- The lease of another A330-200 was announced in December 2016.In January 2013 , Hawaiian signed a Memorandum of Understanding with Airbus for an order of 16 A321neo aircraft plus up to 9 options .
- The movie D.A.R.Y.L . received negative reviews .
- With the mysterious U.S . Senator Eddie Morra ( Bradley Cooper ) providing him with a second drug to counteract NZT 's d...
- Vol . 3 : The Subliminal Verses is by Slipknot and Stone Sour .

Any help would be appreciated, including ideas of tokenizers/ways to quickly deal with this.

Thank you!

**Comment by TalSchuster** [comment]
Hi @apepa,
Thanks for your kind words and interest in our work.

Since we used revisions to Wikipedia, the regular Wiki processing tools didn't always work properly (mostly because of incomplete clauses). We are aware that some sentences remained with some level of noise but figured out that a fact verification system is likely to observe similar noise. But we did implement some scripts to try to automatically clean it as much as possible in order to avoid irrelevant content.

To split to sentences we used spacy and mwparserfromhell:
```
import mwparserfromhell
from spacy.lang.en import English

def strip(text):
    text = text.replace('=', '\=')
    text = mwparserfromhell.parse(text).strip_code()
    text = text.replace('\=', '=')
    return text

    nlp = English()
    sentencizer = nlp.create_pipe("sentencizer")
    nlp.add_pipe(sentencizer)
   nlp(strip(text)).sents
```

We also run additional regex-based cleaning. I've added the file under `preprocessing`.

Let me know if that helps and happy to discuss further according to your specific use case

**Comment by apepa** [comment]
Hi @TalSchuster ,

I definitely see your point about using the text as is, as it would naturally occur.

Thank you for the help with the preprocessing of the text!  It definitely looks cleaner now even though the issue with the abbreviations was still persistent. I managed to find a library for sentence boundary disambiguation (pysbd) that helped with that part though.
